server:
  port: 8188
  servlet:
    context-path: /web-market-auth
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/productsDB
    username: postgres
    password: 739285
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL94Dialect
  h2:
    console:
      enabled: true
jwt:
  secret: laskdjaij4poifjpaijp9sjv98ajpe409pjae84vpea9j0v498jv0a
  lifetime: 360000000
