server:
  port: 5555

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedMethods:
              - GET
              - POST
            allowedHeaders: "*"
      routes:
        - id: core-service
          uri: http://localhost:8189/
          predicates:
            - Path=/gateway/**
          filters:
            - StripPrefix=1
            - PrefixPath=/web-market-core
            - JwtAuthFilter
        - id: order-service
          uri: http://localhost:8186/
          predicates:
            - Path=/order/**
          filters:
            - StripPrefix=1
            - PrefixPath=/web-market-order
            - JwtAuthFilter
        - id: cart-service
          uri: http://localhost:8187/
          predicates:
            - Path=/cart/**
          filters:
            - StripPrefix=1
            - PrefixPath=/web-market-cart
            - JwtAuthFilter
        - id: auth-service
          uri: http://localhost:8188/
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
            - PrefixPath=/web-market-auth
            - JwtAuthFilter

jwt:
  secret: laskdjaij4poifjpaijp9sjv98ajpe409pjae84vpea9j0v498jv0a
