server:
  port: 8187
  servlet:
    context-path: /web-market-cart
spring:
  redis:
    database: 0
    host: localhost
    port: 6379
    password:
  cache:
    default:
      expire-time: 1209600
    user:
      expire-time: 3600
      name: "Cart"